@startuml
!theme cerulean

Rectangle "Champ-Wrestling" <<system>> as system
Actor "Veranstalter" as veranstalter
Actor "Ausrichter" as ausrichter
Actor "Wettkampfbüro" as wkb
Actor "Matte" as matte
Actor "Waage" as waage
Actor "Trainer" as trainer
Actor "Ringer" as ringer
Actor "Offizieller" as offical
Actor "Zuschauer\nInteressierter" as follower
Rectangle "External Cloud DB\nz.B. Ringer-DB" as cloud

veranstalter .do. system
ausrichter .do. system
offical .do. system

trainer .do. system
ringer .do. system
follower .do. system

wkb .up. system
matte .up. system
waage .up. system

cloud .up. system

@enduml
